<?php

namespace Gustavo\IglesiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AutorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutorRepository extends EntityRepository
{
    public function todoOrdenadoXnombre()
    {
        return $this->getEntityManager()
            ->createQuery(
                'select a from IglesiaBundle:Autor a order by a.nombre asc'
            )->getResult();
    }

    public function autorEspec($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT a, i FROM IglesiaBundle:Autor a
                JOIN a.iglesia i
                WHERE a.id = :id'
            )->setParameter('id', $id);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }
}
