<?php

namespace Gustavo\IglesiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IglesiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IglesiaRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function todoOrdenadoXnombre()
    {
         return $this->getEntityManager()
                     ->createQuery(
                                'select i from IglesiaBundle:Iglesia i order by i.nombre asc'
                    )->getResult();
    }

}
