<?php

namespace Gustavo\IglesiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MinisterioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinisterioRepository extends EntityRepository
{
}
