parameters:
#    iglesia.example.class: Gustavo\IglesiaBundle\Example

services:
#    iglesia.example:
#        class: %iglesia.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
